// Scans public/images for product photos and writes src/data/images.js,
// a map of { <productId>: "<extension>" }. The app uses this so it only
// requests images that actually exist — no more 404s in the console.
import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const imagesDir = join(here, "..", "public", "images");
const outFile = join(here, "..", "src", "data", "images.js");

// Preference order when a product has more than one format.
const EXT_PRIORITY = ["png", "jpg", "jpeg", "webp"];

const map = {};
let files = [];
try {
  files = readdirSync(imagesDir);
} catch {
  // images folder missing — that's fine, produce an empty map
}

for (const file of files) {
  const m = file.match(/^(\d+)\.(png|jpe?g|webp)$/i);
  if (!m) continue;
  const id = m[1];
  const ext = m[2].toLowerCase();
  // keep the highest-priority extension if duplicates exist
  const current = map[id];
  if (!current || EXT_PRIORITY.indexOf(ext) < EXT_PRIORITY.indexOf(current)) {
    map[id] = ext;
  }
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  "// AUTO-GENERATED by scripts/gen-images.mjs — do not edit by hand.\n" +
    "// Maps product id -> image file extension for photos that exist.\n" +
    "export const productImages = " +
    JSON.stringify(map, null, 2) +
    ";\n"
);

console.log(`gen-images: ${Object.keys(map).length} product photo(s) found.`);
